export const ClothTypeData = [
  { label: "Abaya", value: "Abaya" },
  { label: "Blouse", value: "Blouse" },
  { label: "Bodysuit", value: "Bodysuit" },
  { label: "Caftan", value: "Caftan" },
  { label: "Cardigan", value: "Cardigan" },
  { label: "Cloak", value: "Cloak" },
  { label: "Coat", value: "Coat" },
  { label: "Dress", value: "Dress" },
  { label: "Dungarees", value: "Dungarees" },
  { label: "Jacket", value: "Jacket" },
  { label: "Jeans", value: "Jeans" },
  { label: "Jumper", value: "Jumper" },
  { label: "Jumpsuit", value: "Jumpsuit" },
  { label: "Leggings", value: "Leggings" },
  { label: "Legwarmers", value: "Legwarmers" },
  { label: "Leotard", value: "Leotard" },
  { label: "Pants / Trousers", value: "Pants / Trousers" },
  { label: "Playsuit", value: "Playsuit" },
  { label: "Poncho", value: "Poncho" },
  { label: "Pajamas", value: "Pajamas" },
  { label: "Sarong", value: "Sarong" },
  { label: "Shawl", value: "Shawl" },
  { label: "Shirt", value: "Shirt" },
  { label: "Shoes", value: "Shoes" },
  { label: "Shorts", value: "Shorts" },
  { label: "Skirt", value: "Skirt" },
  { label: "Sock", value: "Sock" },
  { label: "Sweater", value: "Sweater" },
  { label: "Swimsuit", value: "Swimsuit" },
  { label: "Thoub", value: "Thoub" },
  { label: "Tie", value: "Tie" },
  { label: "Tights", value: "Tights" },
  { label: "Tops", value: "Tops" },
  { label: "Tracksuit", value: "Tracksuit" },
  { label: "T-Shirt", value: "T-Shirt" },
  { label: "Waistcoat", value: "Waistcoat" },
];
export const SizeData = [
  { label: "XS", value: "XS" },
  { label: "S", value: "S" },
  { label: "M", value: "M" },
  { label: "L", value: "L" },
  { label: "XL", value: "XL" },
  { label: "XXL", value: "XXL" },
  { label: "3XL", value: "3XL" },
  { label: "4XL", value: "4XL" },
  { label: "5XL", value: "5XL" },
];
export const ColorData = [
  { label: "Beige", value: "Beige" },
  { label: "Black", value: "Black" },
  { label: "Blue", value: "Blue" },
  { label: "Brown", value: "Brown" },
  { label: "Burgundy", value: "Burgundy" },
  { label: "Checks", value: "Checks" },
  { label: "Gold", value: "Gold" },
  { label: "Green", value: "Green" },
  { label: "Grey", value: "Grey" },
  { label: "Khaki", value: "Khaki" },
  { label: "Multicolor", value: "Multicolor" },
  { label: "Navy", value: "Navy" },
  { label: "Orange", value: "Orange" },
  { label: "Pink", value: "Pink" },
  { label: "Prints", value: "Prints" },
  { label: "Purple", value: "Purple" },
  { label: "Red", value: "Red" },
  { label: "Stripes", value: "Stripes" },
  { label: "White", value: "White" },
  { label: "Yellow", value: "Yellow" },
];
export const GenderData = [
  { label: "Female", value: "Female" },
  { label: "Male", value: "Male" },
];
export const QualityData = [
  { label: "New", value: "New" },
  { label: "Good", value: "Good" },
  { label: "Bad", value: "Bad" },
];
export const AgeCategory = [
  { label: "Baby", value: "Baby" },
  { label: "Kids", value: "Kids" },
  { label: "Teenagers", value: "Teenagers" },
  { label: "Adults", value: "Adults" },
];
